POST http://localhost:8080/api/users
Content-Type: application/json

{
    "password": "laksjdfl",
    "email": "lane@example.com"
}

###
POST http://localhost:8080/api/users

Content-Type: application/json

{
    "password": "jskdljf",
    "email": "anothertest@example.com"
}